researcher_task:
  description: >
    Conduct thorough research on Bitcoin market news and sentiment using the GET_NEWS scraping tool.
    Focus on:
    - Latest market news from Cointelegraph and Cryptonews
    - Analysis of news content and sources
    - Market sentiment indicators from news content
    - Significant events affecting Bitcoin
  expected_output: >
    A comprehensive market research report including:
    - Summary of key market events from news sources
    - Analysis of market sentiment based on news content
    - Impact assessment of recent developments
    - Source attribution and credibility assessment
    - Overall market sentiment conclusion (Bullish/Bearish/Neutral)

technical_analysis_task:
  description: >
    Perform detailed technical analysis of Bitcoin price movements using the CALCULATE_INDICATORS tool.
    Analyze:
    - Key technical indicators from the tool's output:
      * Moving Averages (EMA)
      * MACD and RSI
      * Bollinger Bands
      * Stochastic Oscillator
      * VWAP and ATR
      * ADX and OBV
      * Parabolic SAR
    - Support and resistance levels
    - Market structure
  expected_output: >
    A detailed technical analysis report including:
    - Current market structure analysis
    - Key technical levels and indicators with their interpretations
    - Price action analysis
    - Potential price targets and scenarios
    - Risk assessment
    - Technical analysis conclusion (Buy/Sell/Hold)

decision_task:
  description: >
    Review and synthesize the research and technical analysis reports.
    Make a final trading decision considering:
    - Market research findings
    - Technical analysis results
    - Current position status (using GET_CURRENT_POSITION)
    - Risk factors
    - Market conditions
    Steps:
    1. Check current position using GET_CURRENT_POSITION
    2. If position exists and contradicts the new recommendation:
       - Close existing position using CLOSE_POSITIONS
       - Open new position using EXECUTE_TRADE
    3. If position exists and aligns with recommendation:
       - Hold position
    4. If no position exists:
       - Open new position using EXECUTE_TRADE
  expected_output: >
    A final trading decision report including:
    - Trading recommendation (Buy/Sell/Hold)
    - Detailed reasoning for the decision
    - Current position status
    - Action taken (if any)
    - Entry/exit points (if applicable)
    - Risk management strategy
    - Price targets and stop-loss levels
